version: '3.3'
services:
  frontbizui:
    image: gcr.io/main-project-354317/${APP?Variable not set}:${APP_TAG}
    container_name: ${APP_NAME}
    restart: alwaya
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=80"
      - "traefik.http.routers.${APP_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${APP_NAME}.tls.certresolver=letsencrypt"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_HOSTNAME}`, `www.${APP_HOSTNAME}`)"
networks:
  proxy:
    external:
      name: "traefik-global-proxy"
