version: '3.3'
services:
  frontbizui:
    image: registry.roket.itgage.ru/${APP?Variable not set}:${APP_TAG}
    container_name: ${APP_NAME}
    networks:
      - proxy
    logging:
      driver: json-file
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=80"
      - "traefik.http.routers.${APP_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${APP_NAME}.tls.certresolver=letsencrypt"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_HOSTNAME}`)"
networks:
  proxy:
    external:
      name: "traefik-global-proxy"
