import {Dao} from '~/shared/api/astro';
import type {ChangePolicyProposalFormValues} from '~/shared/api/near/contracts/incoming-options.types';

import {mapAddCouncilOptions} from './map-add-council-options';

describe('Add council options', () => {
  test('return right options for success request', () => {
    const currentDao = {
      isArchived: false,
      createdAt: '2022-07-22T17:37:02.956Z',
      updatedAt: '2022-08-03T11:13:17.570Z',
      transactionHash: '7cjaSMhU3hcCb6RBUG8xb7SHff8MzurVpu5kDxpJrWfZ',
      updateTransactionHash: '6gskkpDfmuqwPpU1tASoZvP9QU39JkqrUvqdVbEhgtXE',
      createTimestamp: '1658511418820114697',
      updateTimestamp: '1659451750072694638',
      id: 'testdaoastro.sputnikv2.testnet',
      config: {
        name: 'testdaoastro',
        purpose: '',
        metadata:
          'eyJsaW5rcyI6W10sImZsYWdDb3ZlciI6IiIsImZsYWdMb2dvIjoiIiwiZGlzcGxheU5hbWUiOiJ0ZXN0ZGFvYXN0cm8iLCJsZWdhbCI6eyJsZWdhbFN0YXR1cyI6IiIsImxlZ2FsTGluayI6IiJ9fQ==',
      },
      metadata: {
        legal: {legalLink: '', legalStatus: ''},
        links: [],
        flagLogo: '',
        flagCover: '',
        displayName: 'testdaoastro',
      },
      amount: '6900678980771030000000000',
      totalSupply: '0',
      lastBountyId: 0,
      lastProposalId: 17,
      stakingContract: '',
      numberOfAssociates: 1,
      numberOfMembers: 3,
      numberOfGroups: 1,
      council: ['extg.testnet', 'rkatarine.testnet', 'extg2.testnet'],
      accountIds: ['extg.testnet', 'rkatarine.testnet', 'extg2.testnet'],
      councilSeats: 3,
      link: '',
      description: '',
      createdBy: 'rkatarine.testnet',
      daoVersionHash: '783vth3Fg8MBBGGFmRqrytQCWBpYzUcmHoCq4Mo8QqF5',
      status: 'Active',
      activeProposalCount: 17,
      totalProposalCount: 18,
      totalDaoFunds: 26.28,
      policy: {
        isArchived: false,
        createdAt: '2022-07-22T17:37:02.956Z',
        updatedAt: '2022-07-22T17:37:02.956Z',
        daoId: 'testdaoastro.sputnikv2.testnet',
        proposalBond: '100000000000000000000000',
        bountyBond: '100000000000000000000000',
        proposalPeriod: '604800000000000',
        bountyForgivenessPeriod: '604800000000000',
        defaultVotePolicy: {weightKind: 'RoleWeight', quorum: '0', kind: 'Ratio', ratio: [1, 2]},
        roles: [
          {
            isArchived: false,
            createdAt: '2022-07-22T17:37:02.956Z',
            updatedAt: '2022-08-03T11:13:17.570Z',
            id: 'testdaoastro.sputnikv2.testnet-council',
            name: 'council',
            kind: 'Group',
            balance: null,
            accountIds: ['extg.testnet', 'rkatarine.testnet', 'extg2.testnet'],
            permissions: [
              'add_member_to_role:AddProposal',
              'bounty_done:VoteApprove',
              'add_bounty:VoteReject',
              'add_bounty:AddProposal',
              'config:VoteReject',
              'add_bounty:VoteApprove',
              'remove_member_from_role:VoteReject',
              'policy:VoteRemove',
              'transfer:VoteRemove',
              'vote:VoteApprove',
              'upgrade_self:VoteApprove',
              'call:VoteRemove',
              'upgrade_self:AddProposal',
              'upgrade_remote:AddProposal',
              'upgrade_remote:VoteReject',
              'upgrade_remote:VoteApprove',
              'vote:AddProposal',
              'add_member_to_role:VoteReject',
              'bounty_done:VoteReject',
              'call:AddProposal',
              'upgrade_self:VoteRemove',
              'add_bounty:VoteRemove',
              'remove_member_from_role:VoteRemove',
              'config:VoteRemove',
              'call:VoteApprove',
              'add_member_to_role:VoteRemove',
              'policy:AddProposal',
              'add_member_to_role:VoteApprove',
              'policy:VoteApprove',
              'transfer:VoteApprove',
              'config:AddProposal',
              '*:Finalize',
              'remove_member_from_role:VoteApprove',
              'set_vote_token:VoteReject',
              'bounty_done:AddProposal',
              'set_vote_token:AddProposal',
              'policy:VoteReject',
              'set_vote_token:VoteRemove',
              'remove_member_from_role:AddProposal',
              'transfer:VoteReject',
              'transfer:AddProposal',
              'call:VoteReject',
              'upgrade_remote:VoteRemove',
              'upgrade_self:VoteReject',
              'vote:VoteReject',
              'bounty_done:VoteRemove',
              'vote:VoteRemove',
              'set_vote_token:VoteApprove',
              'config:VoteApprove',
            ],
            votePolicy: {},
          },
          {
            isArchived: false,
            createdAt: '2022-07-22T17:37:02.956Z',
            updatedAt: '2022-08-03T11:13:17.570Z',
            id: 'testdaoastro.sputnikv2.testnet-all',
            name: 'all',
            kind: 'Everyone',
            balance: null,
            accountIds: null,
            permissions: [
              'upgrade_self:AddProposal',
              'policy:VoteApprove',
              'policy:VoteRemove',
              'call:AddProposal',
              'config:VoteReject',
              'policy:AddProposal',
              'transfer:VoteRemove',
              'add_bounty:AddProposal',
              'config:AddProposal',
              'policy:VoteReject',
              'transfer:AddProposal',
              'add_bounty:VoteApprove',
              'add_bounty:VoteReject',
              'upgrade_self:VoteApprove',
              'upgrade_self:VoteReject',
              'bounty_done:VoteRemove',
              'set_vote_token:VoteApprove',
              'upgrade_remote:VoteApprove',
              'set_vote_token:AddProposal',
              'upgrade_remote:AddProposal',
              'transfer:VoteApprove',
              'add_member_to_role:VoteApprove',
              'remove_member_from_role:VoteRemove',
              'upgrade_remote:VoteReject',
              'call:VoteRemove',
              'add_bounty:VoteRemove',
              'add_member_to_role:VoteRemove',
              'add_member_to_role:VoteReject',
              'call:VoteReject',
              'set_vote_token:VoteReject',
              'vote:VoteApprove',
              'vote:VoteReject',
              'call:VoteApprove',
              'bounty_done:AddProposal',
              'remove_member_from_role:AddProposal',
              'transfer:VoteReject',
              'vote:AddProposal',
              'config:VoteApprove',
              'config:VoteRemove',
              'remove_member_from_role:VoteApprove',
              'bounty_done:VoteReject',
              'upgrade_self:VoteRemove',
              'add_member_to_role:AddProposal',
              'upgrade_remote:VoteRemove',
              'remove_member_from_role:VoteReject',
              'bounty_done:VoteApprove',
              'set_vote_token:VoteRemove',
              'vote:VoteRemove',
            ],
            votePolicy: {},
          },
        ],
      },
      daoVersion: {
        isArchived: false,
        createdAt: '2022-05-18T15:01:39.700Z',
        updatedAt: '2022-05-18T15:01:39.700Z',
        hash: '783vth3Fg8MBBGGFmRqrytQCWBpYzUcmHoCq4Mo8QqF5',
        version: [3, 0],
        commitId: '640495ba572345ca356376989738fbd5462e1ff8',
        changelogUrl: null,
      },
    } as unknown as Dao;

    const formData = {
      type: 'removeCouncil',
      quorum: 10,
      councilAddress: 'barsik.testnet',
      councilList: ['extg.testnet', 'rkatarine.testnet', 'extg2.testnet'],
      amount: '1',
      token: 'near',
      description: 'add barsik.testnet',
      link: '',
      tgas: '150',
    } as unknown as ChangePolicyProposalFormValues;
    expect(mapAddCouncilOptions(currentDao, formData)).toEqual({
      args: {
        proposal: {
          description: 'add barsik.testnet',
          kind: {
            AddMemberToRole: {
              member_id: 'barsik.testnet',
              role: 'council',
            },
          },
        },
      },
      gas: {
        length: 2,
        negative: 0,
        red: null,
        words: [56090624, 447034],
      },
      amount: '100000000000000000000000',
    });
  });
});
