name: ci/cd
on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  publish:
    runs-on:
      - self-hosted
      - Linux

    strategy:
      matrix:
        app:
          - rocketo-bis-ui

    steps:
      - uses: actions/checkout@v2
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.REGISTRY_JSON }}
      - name: Get tag name
        uses: little-core-labs/get-git-tag@v3.0.1
        id: tag-name
      - name: Get short sha
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}})"
        id: extract_branch
      - name: deploy
        uses: fifsky/ssh-action@master
        env:
          TAG_NAME: ${{ steps.tag-name.outputs.tag }}
          APP: ${{ matrix.app }}
          SHORT_SHA: ${{ steps.short-sha.outputs.sha }}
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
        with:
          command: |
            TAG_NAME=${{env.TAG_NAME}}
            APP=${{env.APP}}
            SHORT_SHA=${{env.SHORT_SHA}}
            GIT_BRANCH=${{env.GIT_BRANCH}}
            export
            if [ "$GIT_BRANCH" == "master" ] || [ "$GIT_BRANCH" == "main" ]; then
              APP_NAME=$APP
              APP_TAG=main-$SHORT_SHA
              docker stack deploy -c docker-compose.yaml $APP_NAME --with-registry-auth
            elif [ "$TAG_NAME" != "" ]; then
              APP_NAME=$APP-$TAG_NAME
              APP_TAG=main-$SHORT_SHA
              docker stack deploy -c docker-compose.yaml $APP_NAME --with-registry-auth
            else
              APP_NAME=$APP:branch-$GIT_BRANCH
              APP_TAG=branch-$GIT_BRANCH-$SHORT_SHA
              docker stack deploy -c docker-compose.yaml $APP_NAME --with-registry-auth
            fi
          host: zeus.roke.to
          user: ${{ secrets.ROKETO_DEPLOYER_USER }}
          key: ${{ secrets.ROKETO_DEPLOYER_KEY }}
          args: "-tt"



  success:
    needs:
      - build
      - publish

    runs-on:
      - self-hosted
      - Linux

    steps:
      - run: echo "Done"
