name: ci/cd
on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  build:
    runs-on:
      - self-hosted
      - Linux

    strategy:
      matrix:
        app:
          - rocketo-bis-ui

    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.REGISTRY_JSON }}
      - name: Get tag name
        uses: little-core-labs/get-git-tag@v3.0.1
        id: tag-name
      - name: Get short sha
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
      - name: Set docker tags
        env:
          TAG_NAME: ${{ steps.tag-name.outputs.tag }}
          APP: ${{ matrix.app }}
          SHORT_SHA: ${{ steps.short-sha.outputs.sha }}
        run: |
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo 'DOCKER_TAGS<<EOF' >> $GITHUB_ENV
          if [ "$GIT_BRANCH" == "master" ] || [ "$GIT_BRANCH" == "main" ]; then
            echo "gcr.io/main-project-354317/$APP:latest"
            echo "gcr.io/main-project-354317/$APP:main-$SHORT_SHA"
          elif [ "$TAG_NAME" != "" ]; then
            echo "gcr.io/main-project-354317/$APP:$TAG_NAME"
          else
            echo "gcr.io/main-project-354317/$APP:$GIT_BRANCH"
            echo "gcr.io/main-project-354317/$APP:branch-$GIT_BRANCH-$SHORT_SHA"
          fi >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_TAGS }}

  publish:
    needs:
      - build
    runs-on:
      - self-hosted
      - Linux

    strategy:
      matrix:
        app:
          - rocketo-bis-ui

    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.REGISTRY_JSON }}
      - name: Get tag name
        uses: little-core-labs/get-git-tag@v3.0.1
        id: tag-name
      - name: Get short sha
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
      - name: deploy
        uses: fifsky/ssh-action@master
        env:
          TAG_NAME: ${{ steps.tag-name.outputs.tag }}
          APP: ${{ matrix.app }}
          SHORT_SHA: ${{ steps.short-sha.outputs.sha }}
        with:
          command: |
            GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
            if [ "$GIT_BRANCH" == "master" ] || [ "$GIT_BRANCH" == "main" ]; then
              APP_NAME=$APP
              APP_TAG=main-$SHORT_SHA
              docker stack deploy -c docker-compose.yaml $APP_NAME --with-registry-auth
            elif [ "$TAG_NAME" != "" ]; then
              APP_NAME=$APP-$TAG_NAME
              APP_TAG=main-$SHORT_SHA
              docker stack deploy -c docker-compose.yaml $APP_NAME --with-registry-auth
            else
              APP_NAME=$APP:branch-$GIT_BRANCH
              APP_TAG=branch-$GIT_BRANCH-$SHORT_SHA
              docker stack deploy -c docker-compose.yaml $APP_NAME --with-registry-auth
          host: zeus.roke.to
          user: ${{ secrets.ROKETO_DEPLOYER_USER }}
          key: ${{ secrets.ROKETO_DEPLOYER_KEY }}



  success:
    needs:
      - build
      - publish

    runs-on:
      - self-hosted
      - Linux

    steps:
      - run: echo "Done"
