name: Deploy test [testnet]
on:
  pull_request:
    paths-ignore:
      - '.github/**'
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  near-dapp:
    uses: ./.github/workflows/deploy_reusable.yaml
    with:
      package-name: near-dapp
      app: near-rocketo-bis-ui
      registry: 'gcr.io/main-project-354317/'
      network-variable-name: BUILD_ARG_VITE_NEAR_NETWORK_ID
      network-value: testnet
      app-hostname: near-rocketo-bis-ui.germes.roke.to
      host: germes.roke.to
    secrets: inherit
  solana-dapp:
    uses: ./.github/workflows/deploy_reusable.yaml
    with:
      package-name: solana-dapp
      app: solana-rocketo-bis-ui
      registry: 'gcr.io/main-project-354317/'
      network-variable-name: BUILD_ARG_VITE_SOLANA_NETWORK_ID
      network-value: testnet
      app-hostname: solana-rocketo-bis-ui.germes.roke.to
      host: germes.roke.to
    secrets: inherit
