name: Deploy prod |testnet|
on:
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  near-dapp:
    uses: ./.github/workflows/deploy_reusable.yaml
    with:
      package-name: near-dapp
      app: rocketo-bis-ui-testnet
      registry: 'gcr.io/main-project-354317'
      network-value: testnet
      app-hostname: testnet.app.roke.biz
      host: ares.roke.to
    secrets: inherit
  solana-dapp:
    uses: ./.github/workflows/deploy_reusable.yaml
    with:
      package-name: solana-dapp
      app: solana-rocketo-bis-ui-testnet
      registry: 'gcr.io/main-project-354317'
      network-value: testnet
      app-hostname: testnet.solana.app.roke.biz
      host: ares.roke.to
    secrets: inherit
