name: Deploy test [testnet]
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
  
jobs:
  build-publish:
    uses: ./.github/workflows/deploy_reusable.yaml
    with:
      package-name: near-dapp
      app: rocketo-bis-ui
      network-variable-name: BUILD_ARG_VITE_NEAR_NETWORK_ID
      network-value: testnet
    secrets: inherit
