name: Deploy prod [testnet]
on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  near-dapp:
    uses: ./.github/workflows/deploy_reusable.yaml
    with:
      package-name: near-dapp
      app: rocketo-bis-ui-testnet
      network-variable-name: BUILD_ARG_VITE_NEAR_NETWORK_ID
      network-value: testnet
    secrets: inherit
