name: Deploy prod [mainnet]
on:
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  near-dapp:
    uses: ./.github/workflows/deploy_reusable.yaml
    with:
      package-name: near-dapp
      app: rocketo-bis-ui-prod
      registry: 'gcr.io/main-project-354317'
      network-value: mainnet
      app-hostname: app.roke.biz
      # TODO: When it will be ready remove comment
      # app-hostname: near.app.roke.biz
      host: ares.roke.to
    secrets: inherit
  solana-dapp:
    uses: ./.github/workflows/deploy_reusable.yaml
    with:
      package-name: solana-dapp
      app: solana-rocketo-bis-ui-prod
      registry: 'gcr.io/main-project-354317'
      network-value: mainnet
      app-hostname: solana.app.roke.biz
      host: ares.roke.to
    secrets: inherit
  main-dapp:
    uses: ./.github/workflows/deploy_reusable.yaml
    with:
      package-name: main-dapp
      app: main-rocketo-bis-ui
      registry: 'gcr.io/main-project-354317'
      network-value: mainnet
      app-hostname: main.app.roke.biz
      # TODO: When it will be ready remove comment
      # app-hostname: main.app.roke.biz
      host: ares.roke.to
    secrets: inherit
