name: Quality reusable workflow with matrix strategy

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  QualityReuseableMatrixJob:
    strategy:
      matrix:
        target: ['near-dapp']
    uses: ./.github/workflows/quality.yaml
    with:
      package-name: ${{ matrix.target }}